// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WpfWindow uIWpfWindow = this.UIWpfWindow;
            WpfEdit uIItemEdit = this.UIMainWindowWindow.UIItemCustom.UINewPageFramePane.UIEnteryourcredentialsText.UIItemEdit;
            WpfEdit uIPasswordEdit = this.UIMainWindowWindow.UIItemCustom.UINewPageFramePane.UIPasswordEdit;
            WpfEdit uIPasswordConfirmEdit = this.UIMainWindowWindow.UIItemCustom.UINewPageFramePane.UIPasswordConfirmEdit;
            #endregion

            // Click 'Wpf' window
            Mouse.Click(uIWpfWindow, new Point(495, 214));

            // Type 'hmm2' in first text box next to 'Enter your credentials below' label
            uIItemEdit.Text = this.RecordedMethod1Params.UIItemEditText;

            // Type 'Control + {RMenu}' in first text box next to 'Enter your credentials below' label
            Keyboard.SendKeys(uIItemEdit, this.RecordedMethod1Params.UIItemEditSendKeys, ModifierKeys.Control);

            // Type 'hmm' in first text box next to 'Enter your credentials below' label
            uIItemEdit.Text = this.RecordedMethod1Params.UIItemEditText1;

            // Type 'Alt, Control + 2' in first text box next to 'Enter your credentials below' label
            Keyboard.SendKeys(uIItemEdit, this.RecordedMethod1Params.UIItemEditSendKeys1, (ModifierKeys.Alt | ModifierKeys.Control));

            // Type 'hmm@hmm.com' in first text box next to 'Enter your credentials below' label
            uIItemEdit.Text = this.RecordedMethod1Params.UIItemEditText2;

            // Type '{Tab}' in first text box next to 'Enter your credentials below' label
            Keyboard.SendKeys(uIItemEdit, this.RecordedMethod1Params.UIItemEditSendKeys2, ModifierKeys.None);

            // Type '********' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.RecordedMethod1Params.UIPasswordEditSendKeys, true);

            // Type '********' in 'PasswordConfirm' text box
            Keyboard.SendKeys(uIPasswordConfirmEdit, this.RecordedMethod1Params.UIPasswordConfirmEditSendKeys, true);

            // Click 'Wpf' window
            Mouse.Click(uIWpfWindow, new Point(369, 398));

            // Click 'Wpf' window
            Mouse.Click(uIWpfWindow, new Point(467, 437));
        }
        
        /// <summary>
        /// RegisterEmail - Use 'RegisterEmailParams' to pass parameters into this method.
        /// </summary>
        public void RegisterEmail()
        {
            #region Variable Declarations
            WpfWindow uIWpfWindow = this.UIWpfWindow;
            WpfEdit uIItemEdit = this.UIMainWindowWindow.UIItemCustom.UINewPageFramePane.UIEnteryourcredentialsText.UIItemEdit;
            #endregion

            // Click 'Wpf' window
            Mouse.Click(uIWpfWindow, new Point(496, 218));

            // Type 'person' in first text box next to 'Enter your credentials below' label
            uIItemEdit.Text = this.RegisterEmailParams.UIItemEditText;

            // Type 'Alt, Control + 2' in first text box next to 'Enter your credentials below' label
            Keyboard.SendKeys(uIItemEdit, this.RegisterEmailParams.UIItemEditSendKeys, (ModifierKeys.Alt | ModifierKeys.Control));

            // Type 'person@email.com' in first text box next to 'Enter your credentials below' label
            uIItemEdit.Text = this.RegisterEmailParams.UIItemEditText1;
        }
        
        /// <summary>
        /// RegisterEmail_personmaildotcom - Use 'RegisterEmail_personmaildotcomParams' to pass parameters into this method.
        /// </summary>
        public void RegisterEmail_personmaildotcom()
        {
            #region Variable Declarations
            WpfWindow uIWpfWindow = this.UIWpfWindow;
            WpfEdit uIItemEdit = this.UIMainWindowWindow.UIItemCustom.UINewPageFramePane.UIEnteryourcredentialsText.UIItemEdit;
            WpfPane uICurrentPageFramePane = this.UIMainWindowWindow.UIItemCustom.UICurrentPageFramePane;
            #endregion

            // Click 'Wpf' window
            Mouse.Click(uIWpfWindow, new Point(496, 218));

            // Type 'person' in first text box next to 'Enter your credentials below' label
            uIItemEdit.Text = this.RegisterEmail_personmaildotcomParams.UIItemEditText;

            // Type 'Alt, Control + 2' in first text box next to 'Enter your credentials below' label
            Keyboard.SendKeys(uIItemEdit, this.RegisterEmail_personmaildotcomParams.UIItemEditSendKeys, (ModifierKeys.Alt | ModifierKeys.Control));

            // Type 'person@email.com' in first text box next to 'Enter your credentials below' label
            uIItemEdit.Text = this.RegisterEmail_personmaildotcomParams.UIItemEditText1;

            // Click 'CurrentPageFrame' pane
            Mouse.Click(uICurrentPageFramePane, new Point(537, 227));

            // Type 'person' in first text box next to 'Enter your credentials below' label
            uIItemEdit.Text = this.RegisterEmail_personmaildotcomParams.UIItemEditText2;

            // Type 'Alt, Control + 2' in first text box next to 'Enter your credentials below' label
            Keyboard.SendKeys(uIItemEdit, this.RegisterEmail_personmaildotcomParams.UIItemEditSendKeys1, (ModifierKeys.Alt | ModifierKeys.Control));

            // Type 'person@mail.com' in first text box next to 'Enter your credentials below' label
            uIItemEdit.Text = this.RegisterEmail_personmaildotcomParams.UIItemEditText3;
        }
        
        /// <summary>
        /// RegisterPassword_tester1 - Use 'RegisterPassword_tester1Params' to pass parameters into this method.
        /// </summary>
        public void RegisterPassword_tester1()
        {
            #region Variable Declarations
            WpfPane uICurrentPageFramePane = this.UIMainWindowWindow.UIItemCustom.UICurrentPageFramePane;
            WpfEdit uIPasswordEdit = this.UIMainWindowWindow.UIItemCustom.UINewPageFramePane.UIPasswordEdit;
            #endregion

            // Click 'CurrentPageFrame' pane
            Mouse.Click(uICurrentPageFramePane, new Point(538, 291));

            // Type '********' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.RegisterPassword_tester1Params.UIPasswordEditSendKeys, true);
        }
        
        /// <summary>
        /// RepeatPassword_tester1 - Use 'RepeatPassword_tester1Params' to pass parameters into this method.
        /// </summary>
        public void RepeatPassword_tester1()
        {
            #region Variable Declarations
            WpfPane uICurrentPageFramePane = this.UIMainWindowWindow.UIItemCustom.UICurrentPageFramePane;
            WpfEdit uIPasswordConfirmEdit = this.UIMainWindowWindow.UIItemCustom.UINewPageFramePane.UIPasswordConfirmEdit;
            #endregion

            // Click 'CurrentPageFrame' pane
            Mouse.Click(uICurrentPageFramePane, new Point(557, 357));

            // Type '********' in 'PasswordConfirm' text box
            Keyboard.SendKeys(uIPasswordConfirmEdit, this.RepeatPassword_tester1Params.UIPasswordConfirmEditSendKeys, true);
        }
        
        /// <summary>
        /// CheckAgreeToAllTerms
        /// </summary>
        public void CheckAgreeToAllTerms()
        {
            #region Variable Declarations
            WpfPane uICurrentPageFramePane = this.UIMainWindowWindow.UIItemCustom.UICurrentPageFramePane;
            #endregion

            // Click 'CurrentPageFrame' pane
            Mouse.Click(uICurrentPageFramePane, new Point(308, 395));
        }
        
        /// <summary>
        /// ClickRegister
        /// </summary>
        public void ClickRegister()
        {
            #region Variable Declarations
            WpfPane uICurrentPageFramePane = this.UIMainWindowWindow.UIItemCustom.UICurrentPageFramePane;
            #endregion

            // Click 'CurrentPageFrame' pane
            Mouse.Click(uICurrentPageFramePane, new Point(490, 443));
        }
        
        /// <summary>
        /// AssertPageContainsLoginText - Use 'AssertPageContainsLoginTextExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertPageContainsLoginText()
        {
            #region Variable Declarations
            WpfText uIEnteryourcredentialsText = this.UIMainWindowWindow.UIItemCustom.UINewPageFramePane.UIEnteryourcredentialsText;
            #endregion

            // Verify that the 'Name' property of 'Enter your credentials below' label contains 'Enter your credentials below'
            StringAssert.Contains(uIEnteryourcredentialsText.Name, this.AssertPageContainsLoginTextExpectedValues.UIEnteryourcredentialsTextName);
        }
        
        /// <summary>
        /// NavigateToRegisterUser
        /// </summary>
        public void NavigateToRegisterUser()
        {
            #region Variable Declarations
            WpfPane uICurrentPageFramePane = this.UIMainWindowWindow.UIItemCustom.UICurrentPageFramePane;
            #endregion

            // Click 'CurrentPageFrame' pane
            Mouse.Click(uICurrentPageFramePane, new Point(488, 467));
        }
        
        /// <summary>
        /// RegisterTestUserEmail - Use 'RegisterTestUserEmailParams' to pass parameters into this method.
        /// </summary>
        public void RegisterTestUserEmail()
        {
            #region Variable Declarations
            WpfPane uICurrentPageFramePane = this.UIMainWindowWindow.UIItemCustom.UICurrentPageFramePane;
            WpfEdit uIItemEdit = this.UIMainWindowWindow.UIItemCustom.UINewPageFramePane.UIEnteryourcredentialsText.UIItemEdit;
            #endregion

            // Click 'CurrentPageFrame' pane
            Mouse.Click(uICurrentPageFramePane, new Point(470, 213));

            // Type 'test' in first text box next to 'Enter your credentials below' label
            uIItemEdit.Text = this.RegisterTestUserEmailParams.UIItemEditText;

            // Type 'Alt, Control + 2' in first text box next to 'Enter your credentials below' label
            Keyboard.SendKeys(uIItemEdit, this.RegisterTestUserEmailParams.UIItemEditSendKeys, (ModifierKeys.Alt | ModifierKeys.Control));

            // Type 'test@tester.com' in first text box next to 'Enter your credentials below' label
            uIItemEdit.Text = this.RegisterTestUserEmailParams.UIItemEditText1;
        }
        
        /// <summary>
        /// ClickEmailBox
        /// </summary>
        public void ClickEmailBox()
        {
            #region Variable Declarations
            WpfPane uICurrentPageFramePane = this.UIMainWindowWindow.UIItemCustom.UICurrentPageFramePane;
            #endregion

            // Click 'CurrentPageFrame' pane
            Mouse.Click(uICurrentPageFramePane, new Point(476, 227));
        }
        
        /// <summary>
        /// ClickPasswordBox
        /// </summary>
        public void ClickPasswordBox()
        {
            #region Variable Declarations
            WpfPane uICurrentPageFramePane = this.UIMainWindowWindow.UIItemCustom.UICurrentPageFramePane;
            #endregion

            // Click 'CurrentPageFrame' pane
            Mouse.Click(uICurrentPageFramePane, new Point(508, 287));
        }
        
        /// <summary>
        /// ClickRepeatPasswordBox
        /// </summary>
        public void ClickRepeatPasswordBox()
        {
            #region Variable Declarations
            WpfPane uICurrentPageFramePane = this.UIMainWindowWindow.UIItemCustom.UICurrentPageFramePane;
            #endregion

            // Click 'CurrentPageFrame' pane
            Mouse.Click(uICurrentPageFramePane, new Point(450, 353));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public virtual RegisterEmailParams RegisterEmailParams
        {
            get
            {
                if ((this.mRegisterEmailParams == null))
                {
                    this.mRegisterEmailParams = new RegisterEmailParams();
                }
                return this.mRegisterEmailParams;
            }
        }
        
        public virtual RegisterEmail_personmaildotcomParams RegisterEmail_personmaildotcomParams
        {
            get
            {
                if ((this.mRegisterEmail_personmaildotcomParams == null))
                {
                    this.mRegisterEmail_personmaildotcomParams = new RegisterEmail_personmaildotcomParams();
                }
                return this.mRegisterEmail_personmaildotcomParams;
            }
        }
        
        public virtual RegisterPassword_tester1Params RegisterPassword_tester1Params
        {
            get
            {
                if ((this.mRegisterPassword_tester1Params == null))
                {
                    this.mRegisterPassword_tester1Params = new RegisterPassword_tester1Params();
                }
                return this.mRegisterPassword_tester1Params;
            }
        }
        
        public virtual RepeatPassword_tester1Params RepeatPassword_tester1Params
        {
            get
            {
                if ((this.mRepeatPassword_tester1Params == null))
                {
                    this.mRepeatPassword_tester1Params = new RepeatPassword_tester1Params();
                }
                return this.mRepeatPassword_tester1Params;
            }
        }
        
        public virtual AssertPageContainsLoginTextExpectedValues AssertPageContainsLoginTextExpectedValues
        {
            get
            {
                if ((this.mAssertPageContainsLoginTextExpectedValues == null))
                {
                    this.mAssertPageContainsLoginTextExpectedValues = new AssertPageContainsLoginTextExpectedValues();
                }
                return this.mAssertPageContainsLoginTextExpectedValues;
            }
        }
        
        public virtual RegisterTestUserEmailParams RegisterTestUserEmailParams
        {
            get
            {
                if ((this.mRegisterTestUserEmailParams == null))
                {
                    this.mRegisterTestUserEmailParams = new RegisterTestUserEmailParams();
                }
                return this.mRegisterTestUserEmailParams;
            }
        }
        
        public UIWpfWindow UIWpfWindow
        {
            get
            {
                if ((this.mUIWpfWindow == null))
                {
                    this.mUIWpfWindow = new UIWpfWindow();
                }
                return this.mUIWpfWindow;
            }
        }
        
        public UIMainWindowWindow UIMainWindowWindow
        {
            get
            {
                if ((this.mUIMainWindowWindow == null))
                {
                    this.mUIMainWindowWindow = new UIMainWindowWindow();
                }
                return this.mUIMainWindowWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private RegisterEmailParams mRegisterEmailParams;
        
        private RegisterEmail_personmaildotcomParams mRegisterEmail_personmaildotcomParams;
        
        private RegisterPassword_tester1Params mRegisterPassword_tester1Params;
        
        private RepeatPassword_tester1Params mRepeatPassword_tester1Params;
        
        private AssertPageContainsLoginTextExpectedValues mAssertPageContainsLoginTextExpectedValues;
        
        private RegisterTestUserEmailParams mRegisterTestUserEmailParams;
        
        private UIWpfWindow mUIWpfWindow;
        
        private UIMainWindowWindow mUIMainWindowWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'hmm2' in first text box next to 'Enter your credentials below' label
        /// </summary>
        public string UIItemEditText = "hmm2";
        
        /// <summary>
        /// Type 'Control + {RMenu}' in first text box next to 'Enter your credentials below' label
        /// </summary>
        public string UIItemEditSendKeys = "{RMenu}";
        
        /// <summary>
        /// Type 'hmm' in first text box next to 'Enter your credentials below' label
        /// </summary>
        public string UIItemEditText1 = "hmm";
        
        /// <summary>
        /// Type 'Alt, Control + 2' in first text box next to 'Enter your credentials below' label
        /// </summary>
        public string UIItemEditSendKeys1 = "2";
        
        /// <summary>
        /// Type 'hmm@hmm.com' in first text box next to 'Enter your credentials below' label
        /// </summary>
        public string UIItemEditText2 = "hmm@hmm.com";
        
        /// <summary>
        /// Type '{Tab}' in first text box next to 'Enter your credentials below' label
        /// </summary>
        public string UIItemEditSendKeys2 = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "Dd9ZqbCj8ULSnDiwxpv0Ky4lWKxyXH0D7J5qWtZDBzGJCxMzx+MDMcaEnVxB2jL5CM5ZsWhSPrI=";
        
        /// <summary>
        /// Type '********' in 'PasswordConfirm' text box
        /// </summary>
        public string UIPasswordConfirmEditSendKeys = "bUWtUShvSGlJEfiijNK6HiN/l9ldZwoe";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RegisterEmail'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class RegisterEmailParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'person' in first text box next to 'Enter your credentials below' label
        /// </summary>
        public string UIItemEditText = "person";
        
        /// <summary>
        /// Type 'Alt, Control + 2' in first text box next to 'Enter your credentials below' label
        /// </summary>
        public string UIItemEditSendKeys = "2";
        
        /// <summary>
        /// Type 'person@email.com' in first text box next to 'Enter your credentials below' label
        /// </summary>
        public string UIItemEditText1 = "person@email.com";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RegisterEmail_personmaildotcom'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class RegisterEmail_personmaildotcomParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'person' in first text box next to 'Enter your credentials below' label
        /// </summary>
        public string UIItemEditText = "person";
        
        /// <summary>
        /// Type 'Alt, Control + 2' in first text box next to 'Enter your credentials below' label
        /// </summary>
        public string UIItemEditSendKeys = "2";
        
        /// <summary>
        /// Type 'person@email.com' in first text box next to 'Enter your credentials below' label
        /// </summary>
        public string UIItemEditText1 = "person@email.com";
        
        /// <summary>
        /// Type 'person' in first text box next to 'Enter your credentials below' label
        /// </summary>
        public string UIItemEditText2 = "person";
        
        /// <summary>
        /// Type 'Alt, Control + 2' in first text box next to 'Enter your credentials below' label
        /// </summary>
        public string UIItemEditSendKeys1 = "2";
        
        /// <summary>
        /// Type 'person@mail.com' in first text box next to 'Enter your credentials below' label
        /// </summary>
        public string UIItemEditText3 = "person@mail.com";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RegisterPassword_tester1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class RegisterPassword_tester1Params
    {
        
        #region Fields
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "bUWtUShvSGlJEfiijNK6HiN/l9ldZwoe";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RepeatPassword_tester1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class RepeatPassword_tester1Params
    {
        
        #region Fields
        /// <summary>
        /// Type '********' in 'PasswordConfirm' text box
        /// </summary>
        public string UIPasswordConfirmEditSendKeys = "bUWtUShvSGlJEfiijNK6HiN/l9ldZwoe";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertPageContainsLoginText'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class AssertPageContainsLoginTextExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Name' property of 'Enter your credentials below' label contains 'Enter your credentials below'
        /// </summary>
        public string UIEnteryourcredentialsTextName = "Enter your credentials below";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RegisterTestUserEmail'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class RegisterTestUserEmailParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'test' in first text box next to 'Enter your credentials below' label
        /// </summary>
        public string UIItemEditText = "test";
        
        /// <summary>
        /// Type 'Alt, Control + 2' in first text box next to 'Enter your credentials below' label
        /// </summary>
        public string UIItemEditSendKeys = "2";
        
        /// <summary>
        /// Type 'test@tester.com' in first text box next to 'Enter your credentials below' label
        /// </summary>
        public string UIItemEditText1 = "test@tester.com";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIWpfWindow : WpfWindow
    {
        
        public UIWpfWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            #endregion
        }
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIMainWindowWindow : WpfWindow
    {
        
        public UIMainWindowWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MainWindow";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIItemCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new UIItemCustom(this);
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIItemCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemCustom : WpfCustom
    {
        
        public UIItemCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.PageNavigation";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UINewPageFramePane UINewPageFramePane
        {
            get
            {
                if ((this.mUINewPageFramePane == null))
                {
                    this.mUINewPageFramePane = new UINewPageFramePane(this);
                }
                return this.mUINewPageFramePane;
            }
        }
        
        public WpfPane UICurrentPageFramePane
        {
            get
            {
                if ((this.mUICurrentPageFramePane == null))
                {
                    this.mUICurrentPageFramePane = new WpfPane(this);
                    #region Search Criteria
                    this.mUICurrentPageFramePane.SearchProperties[WpfPane.PropertyNames.ClassName] = "Uia.Frame";
                    this.mUICurrentPageFramePane.SearchProperties[WpfPane.PropertyNames.AutomationId] = "CurrentPageFrame";
                    this.mUICurrentPageFramePane.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUICurrentPageFramePane;
            }
        }
        #endregion
        
        #region Fields
        private UINewPageFramePane mUINewPageFramePane;
        
        private WpfPane mUICurrentPageFramePane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UINewPageFramePane : WpfPane
    {
        
        public UINewPageFramePane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfPane.PropertyNames.ClassName] = "Uia.Frame";
            this.SearchProperties[WpfPane.PropertyNames.AutomationId] = "NewPageFrame";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIEnteryourcredentialsText UIEnteryourcredentialsText
        {
            get
            {
                if ((this.mUIEnteryourcredentialsText == null))
                {
                    this.mUIEnteryourcredentialsText = new UIEnteryourcredentialsText(this);
                }
                return this.mUIEnteryourcredentialsText;
            }
        }
        
        public WpfEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "Password";
                    this.mUIPasswordEdit.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public WpfEdit UIPasswordConfirmEdit
        {
            get
            {
                if ((this.mUIPasswordConfirmEdit == null))
                {
                    this.mUIPasswordConfirmEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIPasswordConfirmEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "PasswordConfirm";
                    this.mUIPasswordConfirmEdit.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIPasswordConfirmEdit;
            }
        }
        #endregion
        
        #region Fields
        private UIEnteryourcredentialsText mUIEnteryourcredentialsText;
        
        private WpfEdit mUIPasswordEdit;
        
        private WpfEdit mUIPasswordConfirmEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIEnteryourcredentialsText : WpfText
    {
        
        public UIEnteryourcredentialsText(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfText.PropertyNames.Name] = "Enter your credentials below";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIItemEdit.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIItemEdit;
        #endregion
    }
}
